import os
import re

mig_dir = 'src/main/resources/DB/migration'
sql_files = [f for f in os.listdir(mig_dir) if f.endswith('.sql')]

for file_name in sql_files:
    path = os.path.join(mig_dir, file_name)
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Replacements
    # 1. AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
    content = re.sub(r'\bAUTO_INCREMENT\b', 'GENERATED BY DEFAULT AS IDENTITY', content, flags=re.IGNORECASE)
    
    # 2. DATETIME -> TIMESTAMP
    content = re.sub(r'\bDATETIME\b', 'TIMESTAMP', content, flags=re.IGNORECASE)
    
    # 3. ON UPDATE CURRENT_TIMESTAMP -> (remove)
    content = re.sub(r'\bON UPDATE CURRENT_TIMESTAMP\b', '', content, flags=re.IGNORECASE)
    
    # 4. JSON is valid in Postgres, BOOLEAN is valid.
    # 5. For double-quotes or backticks if any (MySQL uses backticks for identifiers)
    content = content.replace('', '"')
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

print('SQL Migration scripts successfully converted to PostgreSQL dialect!')
